### ISSUE TITLE
FontFamily

### ISSUE THREAD

**Issue by nikoxd123** [warappa/XamlCSS#35]
Hi, This library work with custom font? If work with custom font, how?

**Comment by warappa** [comment]
Yes, but this is not specific to XamlCSS - you can use custom fonts even without XamlCSS (but with it it's nicer ;) ).

You didn't mention which platform you're targeting, but here's an example for **WPF** and **FontAwesome**:

1. In an WPF project add font to folder "**Assets\fonts**" and set Build-Action to "`Resource`".
2. Add a (s)css for font awesome:
```css
.fa {
    FontFamily: "Assets/fonts/fontawesome-webfont.ttf#FontAwesome";

    &.fa-bars {
        Text: ""; // unicode f0c9
     }
 }
 ```
3. Use these css-classes to apply it to an element like a TextBlock:
```xaml
...
<TextBlock cssWPF:Css.Class="fa fa-bars"></TextBlock>
...
```

**Comment by warappa** [comment]
This question made me realize XamlCSS doesn't understand unicode escapes - created issue #36 "XamlCSS does not support unicode escapes"

**Comment by warappa** [comment]
@nikoxd123 Did this actually answer you question?

**Comment by nikoxd123** [comment]
Thanks, I'll try. I like this library :)

**Comment by nikoxd123** [comment]
PD. The platform on which development is xamarin form.

**Comment by warappa** [comment]
In the commit you see how I integrated FontAwesome in 2 Xamarin.Form test apps (UWP and Android).

In short:

UWP
---
In **UWP project** put font into a path like **`Asset/fonts/fontawesome-webfont.ttf#FontAweseome`** and set **`Build Action`** to **`Content`**.

Android
---
In **Android project** put font into a path like **`Asset/Assets/fonts/fontawesome-webfont.ttf#FontAweseome`** and set **`Build Action`** to **`AndroidAsset`**. (**double** "Assets" is **_no_ error** - it just enables the cross-platform font-path)

Core Xamarin.Forms Project
---
In the common Xamarin.Forms project (if any) add a css like above
```css
.fa {
    FontFamily: "Assets/fonts/fontawesomewebfont.ttf#FontAwesome";
    &.fa-heart { 
        Text: "\f004";
    }
}
```
**Attention**: Escape `&` with `&amp;` if css is embedded in xaml-page!

Assign the style to a Label or something
```xaml
...
<Label cssXF:Css.Class="fa fa-heart"></Label>
...
```
