### ISSUE TITLE
Support Xamarin.Forms Xaml-Previewer

### ISSUE THREAD

**Issue by warappa** [warappa/XamlCSS#5]

**Comment by warappa** [comment]
I have no Visual Studio Enterprise license and therefore cannot develop for it.

Does it already work?

**Comment by brenojab** [comment]
Hi, David! 

I've tried a lot to find any solution for this, but I think the previewer in Visual Studio have a lot of unfixed bugs. I'm using VS 2015 Community in W10 Pro. No solutions util today.

There's many posts at this type in Xamarin's Bugzilla, and a few solutions directly at Visual Studio, but no ones helped me. Many of them referes to use external tools, like Gorilla Player, Genymotion, and others.

I saw your post at Xamarin Forums, and I'm searching for solutions like yours, using CSS in XAML.

Congrats for your implementation, and I keep looking for any XAML previewer solutions.

See ya...

Breno Batista

**Comment by warappa** [comment]
Hi Breno,

I went down the same journey. Being web developer working with html and css, trying to style Xaml with xml ... hurts! ;) It's to verbose, limited,...

If you find a viable previewer, just comment in here, I will take a look.
I have to note, that even for UWP and WPF adding designer-support is hard. WPF seems to work well, UWP has some weird css-selection-problems. So I expect problems in other previewers as well.

PS: **Thanks for your support!**
XamlCSS is still not finished, so I'm happy to see some appreciation for this project!

**Comment by warappa** [comment]
I have not found a way to use the built-in Xamarin.Forms Previewer.
I'm using [LiveXAML](http://livexaml.com/) and it works as expected.
