### ISSUE TITLE
Nice attempt, but too invasive and not prescritive enough

### ISSUE THREAD

**Issue by Joebeazelman** [warappa/XamlCSS#60]

**Comment by warappa** [comment]
Can you give me any details?

**Comment by warappa** [comment]
What exactly do you mean by "too invasive" and "not prescritive enough"?

**Comment by Joebeazelman** [comment]
I commend your efforts, but I was hoping for something that can be plugged into an existing application with minimal coding. Specifically, I was looking for a standard set of style resources and possibly templates to streamline UI development. 

Unfortunately, Microsoft, as always, has done a horrible job with developer guidance.  They have plenty of sample applications, but they all have their own styling conventions.  VSTemplateStudio, for instance, uses a combination of global and inline styles. Windows UWP Samples and UWP Community Toolkit also have their own.  Microsoft documented their UI guidelines, but left it to the developer to implement the specifics.

What you are offering doesn't address this issue. You probably have figured out that XAML was never intended to be hand-coded, which is why Microsoft released Blend and the now defunct Expression.  They left XAML and the developer community in limbo as they tried to cash in on the mobile market.  Having lost in mobile market, they are trying to resurrect it hoping to reinvent Windows. Over the years, the tooling and codebase has been painfully neglected.

You have an opportunity here to lead developers and Microsoft into a better development experience. Why port a horrible style system to replace an even worse one? We don't need anymore cognitive taxation in the way of new nifty tools. Your product only adds another level to the complexity we are dealing with. Why not make our lives easier by allowing us not deal with it at least one major pain point?

It would be worth paying money for a ready made style and template system where the controls, fonts, layouts, etc are neatly styled following Microsoft's guidelines.  Offering a braindead simple utility for visually customizing it would be nice too, but it's not a requirement.  The utility allows for changes to the standard stylesheet by customizing fonts, spacing, colors, etc. Incorporating it into our workflow would be simply a matter of generate the resources, compile the app and run.

Essentially, we want something akin to a Bootstrap for XAML, instead of more cruft and mire to add to our insanely complex workflow. One of the most surprisingly successful software products is Balsamiq.  It's a no frills UI design application that allows you to sketch an interface very quickly.  The feature set is so minimal, it's almost laughable until you realize how it's simplicity adds a quantum leap in productivity. It has been so successful, it became fashionable for startups to emulate their success a few years back.

I hope you take what I am saying seriously. It's no slight on your work.  You deserve at least a good suggestion for your efforts.

**Comment by warappa** [comment]
Thank you for your clarification.

I do web development for a living. 2 years ago I started to look again at WPF and also Xamarin.Forms and was surprised. Surprised that XAML styling doen't offer selectors or freely combinable styles, something so natural in web development. Sure, css is an advanced technology, but if used right it's very versatile, powerful and expressive.

I agree with you, XamlCSS is not what you're looking for. It is not a templating or pre-defined-styles framework, but it was never meant to be. XamlCSS brings css capabilities to xaml, that's it's purpose. It could be the foundation for something like Bootstrap for XAML, but that would be another project.

I guess you would like to have something http://materialdesigninxaml.net/, but for Fluent Design or the like. I hope you find what you are looking for.

Thank you for your thoughts.

**Comment by Joebeazelman** [comment]
Thanks. I saw one called grails and it appears cool, but I don't like their license enforcement scheme.
