### ISSUE TITLE
Can't use CSS that only contains an import

### ISSUE THREAD

**Issue by JohnLouderback** [warappa/XamlCSS#67]
I have an external .scss file that contains the base styles for my application. I'm trying to include it in a static resource stylesheet that imports this external file. If I do that, my static resource CSS fails at the semicolon of the import statement saying that it's an unexpected end of tokens. I don't have the exact error on hand as I'm not home at the moment, but I can provide it later with a code example.

**Comment by warappa** [comment]
Have you checked that you added the assemblies to scan for embedded resources in the Css.Initialize(...) call?
[https://github.com/warappa/XamlCSS/wiki/Css-Imports#important-note](https://github.com/warappa/XamlCSS/wiki/Css-Imports#important-note), 2nd point.

**Comment by JohnLouderback** [comment]
Jeez, my reading comprehension is clearly awful. That seemed to help, but I'm seeing further issues. I think it would be good if the library threw more specific and detail exceptions while parsing.

I'm now getting this:

```
Could not load file or assembly 'I18N, Version=2.0.5.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies

  at System.AppDomain.Load (System.String assemblyString, System.Security.Policy.Evidence assemblySecurity, System.Boolean refonly) [0x00033] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.2/src/mono/mcs/class/corlib/System/AppDomain.cs:801 
  at System.AppDomain.Load (System.String assemblyString) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.2/src/mono/mcs/class/corlib/System/AppDomain.cs:782 
  at System.Reflection.Assembly.Load (System.String assemblyString) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.2/src/mono/mcs/class/corlib/System.Reflection/Assembly.cs:589 
  at System.Text.EncodingHelper.InvokeI18N (System.String name, System.Object[] args) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.2/src/mono/mcs/class/corlib/System.Text/EncodingHelper.cs:131 
```

The whole stacktrace:
![image](https://user-images.githubusercontent.com/4743179/36127834-9fecf300-101c-11e8-8b28-3f1306d5d671.png)

My external .scss file is:
```css
@namespace custom "Radi.CustomControls";

custom|BasicEntry {
  PlaceholderColor: #000; //"{StaticResource BasicEntryBackground}";
}

Label {
  TextColor: #fff;
}
```

The static resource that includes it looks like:
```xaml
      <!-- Global Style Sheet -->
      <css:StyleSheet x:Key="GlobalStyleSheet">
        <css:StyleSheet.Content>
          @import "Styles/Base.scss";
        </css:StyleSheet.Content>
      </css:StyleSheet>
```

For what it's worth, my `Base.scss` file has the following settings:
![image](https://user-images.githubusercontent.com/4743179/36128053-862a1aaa-101d-11e8-8887-96a91b2f4d06.png)


I think my namespace declaration is wrong, but I'm not sure if that's the issue or not since there's no more specific exception thrown. 😞

EDIT: Seems to be failing on this selector `custom|BasicEntry`. I'm going to try to fiddle with my namespace declaration to see if I can get it working. I really wish the exceptions were more specific as to what went wrong with parsing.

EDIT 2: This also fails: 
```css
@namespace custom "Radi.CustomControls, Radi.iOS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null";
```

**Comment by warappa** [comment]
I think the I18N exception should be a catched (aka. "safe") exception - at least that's the case on android. It comes from *AngleSharp* which is used behind the curtains. This is resolved in the latest preview version as I _removed_ the AngleSharp dependency completely. Try update to the preview version and see it it still happens.
https://www.nuget.org/packages/XamlCSS/2.2.0-pre1

Importing embedded scss-files relys on the *default-namespace* (project setting) being _equal_ to the *assembly name* (TLDR: finding the resource is a guesswork). Your assembly is named `Radi.iOS` and your base-namespace seems to be `Radi` - this could be a problem.

Anyway, using the latest preview and writing `*|BasicEntry` should work with _any_ namespace and gives you a clue if the imported file itself is not found by the import-statement.

Regarding Errors:
If you inspect the instance in the debugger, you find the *`Errors` property*, it should provide you with more information.

**Comment by JohnLouderback** [comment]
@warappa I updated to the latest package and wrote the following:
```css
//@namespace custom "Radi.CustomControls, Radi.iOS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null";

*|BasicEntry {
  PlaceholderColor: #000; //"{StaticResource BasicEntryBackground}";
}

Label {
  TextColor: #fff;
}
```
I'm not getting an exception of any kind, but I'm also not seeing my styles applied at all. I'll keep digging in the mean time.

EDIT: For what it's worth, the reason the namespaces are the way they are is a result of how Xamarin Forms shared projects are set up.

EDIT 2: It looks like if I use the same code inside my app resource file xaml file the CSS works, but not when it's in an external file. Going to look into this further.

EDIT 3: The stranger part is that if I make a syntax error (like a forward slash in a selector) I do get an exception in the external file. I was thinking it might have to do with this: https://developer.xamarin.com/guides/xamarin-forms/application-fundamentals/files/#Embedding_in_Shared_Projects but that doesn't seem to be the case since it is parsing the file. If it's worth anything, here's a screenshot of the embedded resources when compiled for iOS: 
<img width="356" alt="snip_20180213121216" src="https://user-images.githubusercontent.com/4743179/36168872-c1fbaa7c-10b7-11e8-9095-9cba419cd977.png">


EDIT 4: Okay, I think I see the issue now. The external file does in fact work correctly now. The problem seems to be that, because it's an embedded resource and is built into the assembly at compile time, changing the external .scss file does not update the view through LiveXAML because the it's not updating the .scss file actually embedded into the assembly of course. Not sure how to work around this though. Does this mean that external .scss files simply won't work with LiveXAML and XamlCss? Maybe there can be some option for using a file from the development machine file system if it's a development build.

**Comment by warappa** [comment]
@Edit 4: Yes, this is a known problem.
The only LiveXAML compatible way is defining the stylesheet in a XAML resource. This gets reloaded and updates the view.

Other than that, having a watch on scss-files would require a Visual Studio extension which would then notify the running app via a REST/WebSocket/... Unfortunately, I have no experience with that so I cannot say when/if I take the chance.

**Comment by JohnLouderback** [comment]
@warappa I might take a stab at a generic library and watcher executable that can communicate changes to embedded resources from the development machine in realtime. I'll let you know how it goes.

**Comment by JohnLouderback** [comment]
@warappa  I know it's been ages, but I'm actually very close to finishing my package for live updating embedded resources. I plan to make a plugin for it specifically for live XAML reloading and live CSS reloading (unless you'd prefer to do so yourself at that time). I've been extremely busy lately, but it shouldn't be long before the initial release. I'm not sure if this bears any meaning to you, but I think it's exciting news.

**Comment by warappa** [comment]
@JohnLouderback Sounds promising, I'm looking forward to it!
What platforms are supported - WPF? Xamarin.Forms? UWP?

**Comment by JohnLouderback** [comment]
For basic embedded resource live updating and handling, all platforms that support embedded resources (which is all platforms). The plugins will exist to add platform specific or otherwise canned behavior, like live reloading XAML or the CSS. There is going to need to a separate Live XAML plugin for each platform, but I think the CSS plugin will be able to be inherently platform independent, unless I'm forgetting something.

**Comment by warappa** [comment]
@JohnLouderback I close this issue due to inactivity.
Feel free to reopen it if you are still working on it. :)
