### ISSUE TITLE
[wiki] Getting Started: Unclear reference to Anglesharp 

### ISSUE THREAD

**Issue by jaredthirsk** [warappa/XamlCSS#68]
"Ensure that the version of AngleSharp is the exact version stated on nuget!"

This does not make sense.  Why bring up AngleSharp all of a sudden?  Is this a mistake?

**Comment by warappa** [comment]
If you're using the latest preview you're right, that doesn't make sense anymore. I removed the dependency in 2.2.0-pre1, but in 2.1.0 and lower it is still required. Documentation updated.

None the less I will also have to further review and update the docs to bring it in better shape.
If you find something feel free to report it!

Thanks for your feedback!
