### ISSUE TITLE
Style not applied to Items defined in Template

### ISSUE THREAD

**Issue by Christoph142** [warappa/XamlCSS#80]
Hi David, XamlCSS seems like a very decent thing to have! :) Unfortunately during my initial test, it didn't work quite the way I expected.
I have a TreeView with an ItemsSource Binding. The items are generated according to an HierarchicalDataTemplate where each item contains multiple controls like Checkboxes, TextBoxes and alike.

Styling the LayerTree itself works, but the TreeViewItems and all the items within defined in the template only works when done via XAML. Trying to do the same via XamlCSS doesn't work at all.

**Comment by warappa** [comment]
@Christoph142 
Thanks for checking out XamlCSS!

Which version are you using? This issue _should_ be fixed since 2.2.0-pre2. If you're not already on it could you try the latest preview version (2.2.0-pre5) and see if it's fixed?

**Comment by Christoph142** [comment]
I tried 2.2.0-pre5 briefly, but it crashed at startup. So no way to check it out right now.

**Comment by warappa** [comment]
@Christoph142 
That's bad. Can you provide me with a reproduction sample of the issue, so I can test and fix it?

**Comment by warappa** [comment]
@Christoph142 
I was able to reproduce your problems.
I just released a new version of **XamlCSS 2.2.0-pre6**. It should fix the app-start crash and support tree-views, but in the selector you need to **append `:visualtree`** so XamlCSS searches your elements on the visual tree. Something like this:

```css
.a-selector:visualtree {
}
```

Please try it and say if it works now for you.

**Comment by Christoph142** [comment]
Wow, that was quick. Thanks a ton @warappa! :)
I'm gonna report back to you whether it works on Monday when I have access to the machine again. 👍

**Comment by Christoph142** [comment]
So, I gave it a try. Mixed results:
1. Crash is fixed :heavy_check_mark: 
2. TreeViewItem style gets now applied (without :visualtree) :heavy_check_mark: 
3. Styling of items within the DataTemplates (with :visualtree selector appended) is totally unpredictable. It doesn't support live editing and whether and which style gets applied to new or existing items seems highly timing related. :x: 
CSS:
`<css:StyleSheet.Content>
            TreeView {
                TreeViewItem {
                    Background: #0F0;
                    Padding: 10;
                    TextBox:visualtree {
                        Foreground: #0F0;
                        Background: #0FF;
                        Margin: 10;
                    }
                }
            }
            .TestingClasses:visualtree { Foreground: #0F0; Background: #F00; Margin: 10; }
        </css:StyleSheet.Content>`
Output:
![image](https://user-images.githubusercontent.com/1440823/44971632-9b28f100-af56-11e8-89bd-173b59ead870.png)

Is there any chance you can make this work without the additional selector?
In XAML, if I e.g. specify that all CheckBoxes should be round, they are no matter where. With the above solution, I'd have to make sure to cover all places separately which is actually exactly the opposite of why I chose XamlCSS in the first place.

**Comment by warappa** [comment]
@Christoph142 
Thanks for re-testing and sharing your results.
I just managed to reproduce the issue. I'm looking into it!

**Comment by warappa** [comment]
@Christoph142 
Just released XamlCSS 2.2.0-pre7 - would you retest it?

**Comment by Christoph142** [comment]
Works like a charm! Thanks so much @warappa. :beers:

**Comment by Christoph142** [comment]
Oh, I got another little issue that should be related / the same: I tried "translating" [this style](https://stackoverflow.com/a/5048141/4566516) into XamlCSS.
It looks like the CornerRadius doesn't get applied to TreeViewItems' Border.

**Comment by warappa** [comment]
I tried that too and currently it's not entirely possible, because MultiTriggers are not supported right now.
Also I found an update-bug, so that parent-nodes are not always corretly updated if a sub-node is added. This causes the "TreeViewItem" selectors not being applied to TreeViewItem-nodes.

MultiTrigger/MultiDataTriggers may take some time. The update-issue will be fixed in the next release.
