### ISSUE TITLE
Trouble with Xamarin DataTemplate

### ISSUE THREAD

**Issue by kiavel** [warappa/XamlCSS#85]
There is an issue with Xamarin DataTemplate.

I tried with this : 
`<ListView ItemsSource="{Binding Source}">
                    <ListView.ItemTemplate>
                        <DataTemplate>
                            <ViewCell>
                                    <Label css:Css.Class="title" Text="test"/>
                            </ViewCell>
                        </DataTemplate>
                    </ListView.ItemTemplate>
                </ListView>`

But Style who was added in App class isn't Applied in this ViewCell.

**Comment by warappa** [comment]
Hi @kiavel 
there is a workaround which was not properly documented. On the `ViewCell` use the `css:VisualTreeCell.Include` attached property and set it's value to `true`.

See the new troubleshooting entry in https://github.com/warappa/XamlCSS/wiki/Troubleshooting for an example.
