### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by a-tk-by** [warappa/XamlCSS#90]
Is .NET Core support planned in future?

**Comment by warappa** [comment]
I just checked: a **WPF .NET Core 3.1 app works with XamlCSS 2.2.0 out of the box**.

The only thing that's _not working_ seems to be the **designer**. I file an issue for that.

Designer workaround: 
Launch your WPF application **with debugge**r and **edit your xaml files** while debugging, that **updates the app in real time**.

**Comment by fugaku** [comment]
Any sample code for WPF on .NET Core 3.1 ?
I saw the Getting Started using XamlCSS.WPF which support .NET Framework only.
