### ISSUE TITLE
XamlCSS vs XamarinForms css

### ISSUE THREAD

**Issue by michelevirgilio** [warappa/XamlCSS#99]
Hi, would be better to use your XamlCSS instead of native css support of Xamarin Forms? What are the advantages?
Thanks

**Comment by warappa** [comment]
Hi @michelevirgilio ,
in Xamarin.Forms native CSS you can only use some of all dependency properties, in XamlCSS every one.
Xamarin.Forms CSS requires that a dependency property is explicitly mapped, XamlCSS doesn't require any mapping.
Xamarin.Forms tries to mimic the web CSS and remaps i.e. "FontFamily" to web's "font-family", in XamlCSS every dependency property is named like it's named in your XAML file. Even your custom dependency properties are supported without any mapping.

Have a look at this page for examples:
https://github.com/warappa/XamlCSS/wiki/Why-CSS-for-Xaml%3F

I hope this helps you.

**Comment by michelevirgilio** [comment]
Thank you, very explicative and very interesting!
